{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{ezscript_require( array( 'nxc-cache-block.js' ) )}
{ezcss_require( array( 'nxc-cache-block.css' ) )}
<a id="{$id}" class="nxc-cache-block-ajax-onload-link" href="{$nxc_cache_block_uri}" {if $callback}callback="{$callback}"{/if}>&nbsp;</a>
